# coding: utf-8
"""
To prevent the simulations from accidentally being rerun, there are lock files
(e.g. lock_G.flag) that are saved in the simulation directory. To rerun the
simulation, remove the lock file.
(The reason for this is that different projects share the same simulations so
 that the results are comparable. We don't want one project to accidentally
 erase simulations that another project depends on.)
"""
import shutil

import pandas as pd

from pathlib import Path
from itertools import combinations

configfile: 'workflow/config/config.yaml'
include: 'rules/zombi.smk'


#-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-
# Targets
#-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-

rule all:
  input:
    buildAllTargetList

