name: zombi
channels:                                                                       
  - conda-forge                                                                 
  - bioconda
  - default
dependencies:
  - snakemake
  - numpy
  - flask
  - networkx
  - pybedtools
  - biopython
  - bcbio-gff
  - ete3
  - pytest
  - pytest-console-scripts
  - pytest-dependency
  - pytest-repeat
  - pip
  - pip:
    - pyvolve>=1.0.1
