[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project]
name = "zombi"
version = "2.0.0a0"
description = "A phylogenetic simulator of trees, genomes and sequences that accounts for dead lineages"
authors = [{name = "Adrián A. Davín", email = "aaredav@gmail.com"}, {name= "Krister M. Swenson", email = "swenson@lirmm.fr"}]
requires-python = ">=3.8"
readme = "README.md"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Programming Language :: Python :: 3",
]
dependencies = [
    "numpy",
    "flask",
    "networkx",
    "pybedtools",
    "biopython",
    "bcbio-gff",
    "ete3",
    "pyvolve>=1.0.1",
]

[project.urls]
Homepage = "https://github.com/AADavin/Zombi"
Issues = "https://github.com/AADavin/Zombi/issues"

[tool.hatch.build.targets.sdist]
include = ["src/zombi"]

[tool.hatch.build.targets.wheel]
packages = ["src/zombi"]

[tool.hatch.build.targets.wheel.shared-data]
"Parameters" = "share/zombi/Parameters"
"Tutorials" = "share/zombi/Tutorials"
"Validations" = "share/zombi/Validations" 
"workflow" = "share/zombi/workflow"

[project.scripts]
zombiRateCustomizer = "zombi.scripts.zombiRateCustomizer:main"
zombiSpeciesSampler = "zombi.scripts.zombiSpeciesSampler:main"
zombi = "zombi.scripts.zombi:main"
zombiExporter = "zombi.scripts.zombiExporter:main"
zombiStats = "zombi.scripts.zombiStats:main"
zombiGenerator = "zombi.scripts.zombiGenerator:main"
